version: "3.8"

services:
  contrato-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contrato-service
    ports:
      - "8004:8004"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/sisdb2025
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sisdb2025
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
