version: '3.8'

services:
  contrato:
    build:
      context: .
    ports:
      - "8003:8003"
    networks:
      - micro_network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_container:3306/sisdb2025
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: mysql:8
    container_name: db_container # Nuevo nombre del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sisdb2025
    ports:
      - "3306:3306"
    networks:
      - micro_network
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80" # PhpMyAdmin se abrirá en localhost:8080
    environment:
      PMA_HOST: db_container
      PMA_USER: root
      PMA_PASSWORD: 123
    depends_on:
      - db
    networks:
      - micro_network

networks:
  micro_network:
    driver: bridge

volumes:
  db_data:
